'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ArrowRight,
  Menu,
  X,
  Calendar,
  Leaf,
  CheckCircle2,
  ChevronDown,
  Layers,
  FileText,
  LineChart,
  Sprout,
  Factory,
  Truck,
  Activity,
  Recycle,
  ShieldCheck,
  Award
} from 'lucide-react';
import Footer from '@/components/Footer';
import { HeroFadeDown, HeroFadeUp, FadeUp, StaggerContainer, StaggerItem } from '@/components/ui/Motion';

const NAV_LINKS = [
  { href: '/corporate', label: 'Corporate' },
  { href: '/cleantech', label: 'Clean Tech' },
  { href: '/climate-finance', label: 'Climate Finance' },
  { href: '/tools/ghg-calculator', label: 'GHG Calculator' },
];

const CORE_SERVICES = [
  {
    title: 'Product Carbon Footprint (PCF)',
    description: 'Calculate the total greenhouse gas emissions generated by your product across its lifespan, aligned with ISO 14067 and GHG Protocol Product Standard.',
    icon: <Leaf className="h-6 w-6" />,
    accent: 'text-emerald-500',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20'
  },
  {
    title: 'Life Cycle Assessment (LCA)',
    description: 'A comprehensive multi-criteria evaluation of environmental impacts beyond just carbon (water, land use, toxicity) from cradle to grave.',
    icon: <Layers className="h-6 w-6" />,
    accent: 'text-blue-500',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20'
  },
  {
    title: 'Environmental Product Declaration (EPD)',
    description: 'Third-party verified, standardized documents communicating transparent, comparable data about the environmental impact of your products.',
    icon: <Award className="h-6 w-6" />,
    accent: 'text-purple-500',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20'
  },
];

const LCA_STAGES = [
  {
    stage: 'Raw Materials',
    title: 'Extraction & Processing',
    description: 'Impact of sourcing raw materials, including mining, farming, and preliminary processing.',
    icon: <Sprout className="h-8 w-8" />,
    color: 'from-green-400 to-emerald-500'
  },
  {
    stage: 'Manufacturing',
    title: 'Production Phase',
    description: 'Energy use, emissions, and waste generated during the actual manufacturing of the product.',
    icon: <Factory className="h-8 w-8" />,
    color: 'from-blue-400 to-cyan-500'
  },
  {
    stage: 'Transport',
    title: 'Distribution',
    description: 'Logistics, packaging, and fuel emissions required to move the product to the end user.',
    icon: <Truck className="h-8 w-8" />,
    color: 'from-amber-400 to-orange-500'
  },
  {
    stage: 'Use',
    title: 'Consumer Phase',
    description: 'Environmental impact during the product\'s active lifespan (e.g., electricity used by an appliance).',
    icon: <Activity className="h-8 w-8" />,
    color: 'from-rose-400 to-red-500'
  },
  {
    stage: 'End-of-Life',
    title: 'Disposal & Recycling',
    description: 'Impacts associated with landfilling, incineration, or the benefits of recycling the product.',
    icon: <Recycle className="h-8 w-8" />,
    color: 'from-purple-400 to-indigo-500'
  }
];

const DELIVERABLES = [
  {
    title: 'Footprint Report',
    description: 'Detailed breakdown of your product\'s emissions profile, identifying hotspots in the supply chain.',
    icon: <FileText className="h-6 w-6" />,
    accent: 'from-emerald-500 to-green-600',
  },
  {
    title: 'EPD Documentation',
    description: 'Ready-to-publish, verified declarations conforming to ISO 14025 standards for B2B procurement.',
    icon: <ShieldCheck className="h-6 w-6" />,
    accent: 'from-blue-500 to-cyan-600',
  },
  {
    title: 'Reduction Roadmap',
    description: 'Actionable strategies for eco-design, alternative materials, and efficiency improvements.',
    icon: <LineChart className="h-6 w-6" />,
    accent: 'from-primary-500 to-primary-700',
  },
];

const FAQS = [
  {
    question: 'What is the difference between PCF and LCA?',
    answer: 'A Product Carbon Footprint (PCF) specifically measures greenhouse gas emissions (carbon footprint) associated with a product. A Life Cycle Assessment (LCA) is broader, evaluating multiple environmental impacts such as water usage, land acidification, and ozone depletion alongside carbon emissions.',
  },
  {
    question: 'Why do I need an EPD?',
    answer: 'An Environmental Product Declaration (EPD) is increasingly required in green public procurement, construction (e.g., LEED certification), and B2B supply chains. It acts as a standardized "nutrition label" for the environmental impact of your product.',
  },
  {
    question: 'How long does an LCA or EPD take?',
    answer: 'The process typically takes 3 to 6 months, depending on the complexity of your product, the availability of primary data from your suppliers, and the third-party verification timelines for EPDs.',
  },
  {
    question: 'Do you help with primary data collection?',
    answer: 'Yes. We provide data collection templates and guide your suppliers on how to provide the necessary energy, material, and transport data to ensure a high-quality assessment.',
  }
];

export default function ProductLCAPage() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  useEffect(() => {
    if (!mobileNavOpen) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = previousOverflow; };
  }, [mobileNavOpen]);

  const scrollToLeadCapture = (e: React.MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault();
    document.getElementById('lead-capture')?.scrollIntoView({ behavior: 'smooth' });
  };

  return (
    <div className="page-shell min-h-screen bg-slate-50">
      {/* Navbar */}
      <HeroFadeDown delay={0} className="sticky top-0 z-50">
        <header className="border-b border-white/10 bg-white/80 backdrop-blur-xl shadow-sm">
          <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8">
            <div className="flex flex-1 items-center justify-start min-w-0">
              <Link href="/" className="flex min-w-0 items-center gap-3">
                <Image src="/images/logo.jpeg" alt="Ploxi Earth" width={42} height={42} className="flex-shrink-0 rounded-full ring-2 ring-primary-500/10" />
                <div className="min-w-0">
                  <span className="block truncate text-lg font-bold text-gray-900">Ploxi Earth</span>
                  <span className="hidden text-xs uppercase tracking-[0.22em] text-gray-400 xl:block">
                    Decarbonisation Marketplace
                  </span>
                </div>
              </Link>
            </div>
            <nav className="hidden lg:flex flex-shrink-0 items-center justify-center gap-1 xl:gap-4">
              {NAV_LINKS.map((item) => (
                <Link key={item.href} href={item.href} className="whitespace-nowrap rounded-full px-3 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-100 hover:text-primary-600 xl:px-4">
                  {item.label}
                </Link>
              ))}
            </nav>
            <div className="flex flex-1 items-center justify-end gap-3">
              <div className="hidden lg:flex items-center gap-2 xl:gap-3">
                <a href="#lead-capture" onClick={scrollToLeadCapture} className="btn-primary flex whitespace-nowrap items-center gap-2 px-4 py-2 text-sm transition-transform hover:-translate-y-0.5">
                  <Calendar className="h-4 w-4" />
                  Book Assessment
                </a>
              </div>
              <button type="button" onClick={() => setMobileNavOpen(true)} className="inline-flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-2xl border border-gray-200 bg-white text-gray-700 shadow-sm transition-colors hover:bg-gray-50 lg:hidden" aria-label="Open navigation">
                <Menu className="h-5 w-5" />
              </button>
            </div>
          </div>
        </header>
      </HeroFadeDown>

      {/* Mobile Nav */}
      <AnimatePresence>
        {mobileNavOpen && (
          <>
            <motion.button type="button" aria-label="Close navigation" className="fixed inset-0 z-[60] bg-slate-950/45 backdrop-blur-sm lg:hidden" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setMobileNavOpen(false)} />
            <motion.div className="fixed inset-x-4 top-4 z-[70] overflow-hidden rounded-[28px] border border-white/60 bg-white/95 p-4 shadow-2xl backdrop-blur-xl lg:hidden" initial={{ opacity: 0, y: -24, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -18, scale: 0.98 }} transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}>
              <div className="mb-4 flex items-center justify-between gap-3">
                <div className="flex min-w-0 items-center gap-3">
                  <Image src="/images/logo.jpeg" alt="Ploxi Earth" width={38} height={38} className="rounded-full" />
                  <div className="min-w-0">
                    <p className="truncate text-sm font-bold text-slate-900">Ploxi Earth</p>
                  </div>
                </div>
                <button type="button" onClick={() => setMobileNavOpen(false)} className="inline-flex h-10 w-10 items-center justify-center rounded-2xl border border-slate-200 text-slate-600 transition-colors hover:bg-slate-50">
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="space-y-2">
                {NAV_LINKS.map((item) => (
                  <Link key={item.href} href={item.href} onClick={() => setMobileNavOpen(false)} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-sm font-medium text-slate-700 transition-colors hover:border-primary-200 hover:bg-primary-50 hover:text-primary-700">
                    <span>{item.label}</span>
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                ))}
              </div>
              <div className="mt-4 flex flex-col gap-3">
                <a href="#lead-capture" onClick={(e) => { setMobileNavOpen(false); scrollToLeadCapture(e); }} className="btn-primary flex w-full items-center justify-center gap-2 transition-transform hover:-translate-y-0.5">
                  <Calendar className="h-4 w-4" />
                  Book Assessment
                </a>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Hero Section */}
      <section className="relative overflow-hidden bg-slate-950 text-white pb-24 pt-20 lg:pt-28">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-primary-900/30 via-slate-950 to-slate-950" />
        <div className="absolute right-0 top-1/2 -translate-y-1/2 h-96 w-96 rounded-full bg-cyan-500/10 blur-[120px]" />

        <div className="relative mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8 z-10">
          <HeroFadeUp delay={0.1}>
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-500/15 px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">
              Manufacturers & Exporters
            </div>
          </HeroFadeUp>
          <HeroFadeUp delay={0.2}>
            <h1 className="mt-8 text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-7xl text-balance">
              Measure Product Impact Across the <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-300">Entire Lifecycle.</span>
            </h1>
          </HeroFadeUp>
          <HeroFadeUp delay={0.3}>
            <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">
              From carbon footprinting to EPD documentation, build transparent, verifiable environmental performance data to satisfy supply chain demands.
            </p>
          </HeroFadeUp>
          <HeroFadeUp delay={0.4}>
            <div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row">
              <a href="#lead-capture" onClick={scrollToLeadCapture} className="btn-primary px-8 py-4 text-base font-semibold shadow-lg shadow-emerald-600/20">
                Book Carbon Assessment
              </a>
              <a href="#lifecycle" onClick={(e) => { e.preventDefault(); document.getElementById('lifecycle')?.scrollIntoView({ behavior: 'smooth' }); }} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/5 px-8 py-4 text-base font-semibold text-white transition-all hover:bg-white/10">
                Explore LCA Stages
              </a>
            </div>
          </HeroFadeUp>
        </div>
      </section>

      {/* Core Services Explanation */}
      <section className="bg-slate-50 py-24">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
              Understand Your Product's Footprint
            </h2>
            <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
              We provide the full spectrum of product-level environmental analyses required by modern B2B buyers and regulators.
            </p>
          </FadeUp>

          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {CORE_SERVICES.map((service) => (
              <StaggerItem key={service.title} className="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm hover:shadow-md transition">
                <div className={`mb-6 inline-flex h-16 w-16 items-center justify-center rounded-2xl ${service.bg} border ${service.border} ${service.accent}`}>
                  {service.icon}
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-4">{service.title}</h3>
                <p className="text-gray-600 leading-relaxed">{service.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* Product Lifecycle Visualization */}
      <section id="lifecycle" className="bg-white py-24 overflow-hidden border-t border-gray-100">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 text-center">
          <FadeUp>
            <h2 className="text-3xl font-bold tracking-tight text-gray-900">
              The "Cradle-to-Grave" Journey
            </h2>
            <p className="mt-4 text-lg text-gray-600 max-w-3xl mx-auto mb-16">
              A true LCA analyzes the environmental interventions at every single stage of your product's life.
            </p>
          </FadeUp>

          {/* Desktop Timeline */}
          <div className="hidden lg:flex items-center justify-between relative">
            <div className="absolute top-1/2 left-0 right-0 h-1 bg-gray-100 -translate-y-1/2 z-0" />
            
            {LCA_STAGES.map((stage, idx) => (
              <FadeUp key={idx} delay={idx * 0.1} className="relative z-10 flex flex-col items-center w-48">
                <div className="text-sm font-bold text-gray-400 mb-4 uppercase tracking-wider">{stage.stage}</div>
                <div className={`w-20 h-20 rounded-full bg-gradient-to-br ${stage.color} text-white flex items-center justify-center shadow-lg transform transition hover:scale-110 mb-4`}>
                  {stage.icon}
                </div>
                <div className="text-center">
                  <h4 className="font-bold text-gray-900 mb-1">{stage.title}</h4>
                  <p className="text-xs text-gray-500 leading-relaxed px-2">{stage.description}</p>
                </div>
              </FadeUp>
            ))}
          </div>

          {/* Mobile/Tablet Timeline */}
          <div className="lg:hidden space-y-8 relative">
            <div className="absolute left-10 top-0 bottom-0 w-1 bg-gray-100 z-0" />
            {LCA_STAGES.map((stage, idx) => (
              <FadeUp key={idx} delay={idx * 0.1} className="relative z-10 flex items-center text-left gap-6">
                <div className={`w-20 h-20 flex-shrink-0 rounded-full bg-gradient-to-br ${stage.color} text-white flex items-center justify-center shadow-lg`}>
                  {stage.icon}
                </div>
                <div>
                  <div className="text-xs font-bold text-gray-400 uppercase tracking-wider">{stage.stage}</div>
                  <h4 className="font-bold text-gray-900 mb-1">{stage.title}</h4>
                  <p className="text-sm text-gray-500">{stage.description}</p>
                </div>
              </FadeUp>
            ))}
          </div>
        </div>
      </section>

      {/* Deliverables Section */}
      <section className="bg-slate-900 py-24 text-white relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary-900/20 rounded-full blur-[100px] pointer-events-none" />
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 relative z-10">
          <FadeUp className="text-center mb-16">
            <h2 className="text-3xl font-bold">What We Deliver</h2>
            <p className="mt-4 text-slate-400 text-lg">Actionable outputs ready for B2B procurement and compliance.</p>
          </FadeUp>
          
          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {DELIVERABLES.map((item) => (
              <StaggerItem key={item.title} className="bg-slate-800 rounded-3xl p-8 border border-slate-700 hover:-translate-y-1 transition duration-300">
                <div className={`mb-6 inline-flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br ${item.accent} text-white shadow-inner`}>
                  {item.icon}
                </div>
                <h3 className="text-xl font-bold text-white mb-3">{item.title}</h3>
                <p className="text-slate-400">{item.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* FAQs */}
      <section className="bg-slate-50 py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900">Frequently Asked Questions</h2>
          </FadeUp>
          <div className="space-y-4">
            {FAQS.map((faq, idx) => (
              <div key={idx} className="bg-white border border-gray-200 rounded-2xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-6 py-5 flex items-center justify-between font-semibold text-gray-900 hover:bg-gray-50 transition"
                >
                  <span className="text-left">{faq.question}</span>
                  <ChevronDown className={`h-5 w-5 text-gray-500 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                <AnimatePresence>
                  {openFaq === idx && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="px-6 pb-5 text-gray-600 text-sm"
                    >
                      {faq.answer}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Lead Capture Form Section */}
      <section id="lead-capture" className="bg-white py-24 relative overflow-hidden">
        <div className="absolute left-0 top-0 h-full w-1/3 bg-gradient-to-r from-emerald-50 to-white pointer-events-none" />
        
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="bg-slate-900 rounded-[2.5rem] overflow-hidden shadow-2xl flex flex-col lg:flex-row-reverse">
            {/* Right Info */}
            <div className="lg:w-5/12 p-10 sm:p-14 bg-gradient-to-bl from-emerald-900 to-slate-900 text-white flex flex-col justify-center">
              <Layers className="h-12 w-12 text-emerald-400 mb-6" />
              <h2 className="text-3xl font-bold mb-4">Book Your Carbon Assessment</h2>
              <p className="text-emerald-100/80 mb-8">
                Ready to measure your product's impact? Provide some details about your product line and our LCA experts will prepare a custom proposal.
              </p>
              <div className="space-y-4">
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> ISO 14040/44 Compliant
                </div>
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Primary data support
                </div>
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Verification assistance
                </div>
              </div>
            </div>

            {/* Left Form */}
            <div className="lg:w-7/12 p-10 sm:p-14 bg-white">
              <form className="space-y-6" onSubmit={(e) => e.preventDefault()}>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="name" className="text-sm font-medium text-gray-700">Full Name</label>
                    <input type="text" id="name" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="Jane Smith" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="email" className="text-sm font-medium text-gray-700">Work Email</label>
                    <input type="email" id="email" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="jane@company.com" />
                  </div>
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="company" className="text-sm font-medium text-gray-700">Company Name</label>
                    <input type="text" id="company" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="Acme Manufacturing" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="industry" className="text-sm font-medium text-gray-700">Industry</label>
                    <select id="industry" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm bg-white focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition text-gray-700">
                      <option value="">Select Industry</option>
                      <option value="manufacturing">Manufacturing & Industrial</option>
                      <option value="construction">Construction Materials</option>
                      <option value="consumer">Consumer Goods</option>
                      <option value="electronics">Electronics</option>
                      <option value="other">Other</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-2">
                  <label htmlFor="productDetails" className="text-sm font-medium text-gray-700">Product Details & Goals</label>
                  <textarea id="productDetails" rows={4} className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition resize-none" placeholder="Tell us briefly about the product(s) you want to assess and your primary goal (e.g., EPD certification, buyer request)..."></textarea>
                </div>

                <button type="submit" className="btn-primary w-full py-4 text-base font-semibold shadow-md">
                  Request Assessment Proposal
                </button>
                <p className="text-xs text-center text-gray-500 mt-4">
                  By submitting this form, you agree to our privacy policy.
                </p>
              </form>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
