'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ArrowRight,
  Menu,
  X,
  CheckCircle2,
  ChevronDown,
  Sun,
  Wind,
  BatteryCharging,
  Calculator,
  Banknote,
  TrendingDown,
  Calendar,
  PieChart,
  Leaf,
  Briefcase
} from 'lucide-react';
import Footer from '@/components/Footer';
import { HeroFadeDown, HeroFadeUp, FadeUp, StaggerContainer, StaggerItem } from '@/components/ui/Motion';

const NAV_LINKS = [
  { href: '/corporate', label: 'Corporate' },
  { href: '/cleantech', label: 'Clean Tech' },
  { href: '/climate-finance', label: 'Climate Finance' },
  { href: '/tools/ghg-calculator', label: 'GHG Calculator' },
];

const FINANCING_OPTIONS = [
  {
    title: 'Power Purchase Agreements (PPA)',
    description: 'Zero upfront cost. You agree to purchase the power generated by the solar system at a fixed, lower rate than the grid for 15-25 years.',
    icon: <Briefcase className="h-6 w-6" />,
    accent: 'text-emerald-500',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20'
  },
  {
    title: 'Green Loans / CAPEX',
    description: 'Direct ownership of the asset using tailored green financing. Claim 100% of the tax incentives, depreciation benefits, and long-term free energy.',
    icon: <Banknote className="h-6 w-6" />,
    accent: 'text-blue-500',
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20'
  },
  {
    title: 'Operating Leases',
    description: 'Pay a fixed monthly fee to lease the equipment. Immediate utility savings often outweigh the lease payment, generating instant positive cash flow.',
    icon: <PieChart className="h-6 w-6" />,
    accent: 'text-purple-500',
    bg: 'bg-purple-500/10',
    border: 'border-purple-500/20'
  },
];

const PROJECT_EXAMPLES = [
  {
    title: 'Commercial Solar',
    description: 'Rooftop, ground-mount, and carport solar arrays for factories, warehouses, and corporate campuses.',
    icon: <Sun className="h-8 w-8" />,
    color: 'from-amber-400 to-orange-500'
  },
  {
    title: 'Wind Energy',
    description: 'Utility-scale and distributed wind projects providing high-yield renewable baseload generation.',
    icon: <Wind className="h-8 w-8" />,
    color: 'from-blue-400 to-cyan-500'
  },
  {
    title: 'Battery Energy Storage (BESS)',
    description: 'Peak shaving, grid resilience, and load shifting to maximize the value of intermittent renewable generation.',
    icon: <BatteryCharging className="h-8 w-8" />,
    color: 'from-emerald-400 to-teal-500'
  }
];

const WORKFLOW = [
  { step: '1', title: 'Energy Profiling', desc: 'We analyze your 12-month utility interval data to determine optimal system size.' },
  { step: '2', title: 'Financial Modeling', desc: 'Comparing PPA, Lease, and Loan options to find your highest ROI pathway.' },
  { step: '3', title: 'Lender Matching', desc: 'Connecting you with our network of specialized green lenders and climate funds.' },
  { step: '4', title: 'Deployment', desc: 'Securing capital and proceeding to EPC contracting and construction.' },
];

const FAQS = [
  {
    question: 'What is a Power Purchase Agreement (PPA)?',
    answer: 'A PPA is a financial arrangement where a third-party developer owns, operates, and maintains the photovoltaic (PV) system, and you agree to site the system on your property and purchase the system\'s electric output for a predetermined period.',
  },
  {
    question: 'Are there government tax incentives available?',
    answer: 'Yes, depending on your jurisdiction, there are substantial incentives. For example, in the US, the Investment Tax Credit (ITC) offers a 30%+ tax credit. We factor all available local and national incentives into your financial model.',
  },
  {
    question: 'How long does the financing approval take?',
    answer: 'Standard green loan or lease approvals typically take 2-4 weeks once all financial data is submitted. Complex, large-scale PPAs may take 2-3 months to fully execute.',
  },
  {
    question: 'Will solar actually save me money?',
    answer: 'Yes. With utility rates historically rising 3-5% annually, locking in a lower, fixed energy rate through a PPA or eliminating your bill through ownership yields millions in long-term savings for commercial facilities.',
  }
];

export default function RenewableFinancingPage() {
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [sliderValue, setSliderValue] = useState(15000); // Monthly bill mock

  useEffect(() => {
    if (!mobileNavOpen) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => { document.body.style.overflow = previousOverflow; };
  }, [mobileNavOpen]);

  const scrollToLeadCapture = (e: React.MouseEvent<HTMLAnchorElement>) => {
    e.preventDefault();
    document.getElementById('lead-capture')?.scrollIntoView({ behavior: 'smooth' });
  };

  const calculatedSavings = (sliderValue * 12 * 0.4 * 20).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

  return (
    <div className="page-shell min-h-screen bg-slate-50">
      {/* Navbar */}
      <HeroFadeDown delay={0} className="sticky top-0 z-50">
        <header className="border-b border-white/10 bg-white/80 backdrop-blur-xl shadow-sm">
          <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6 lg:px-8">
            <div className="flex flex-1 items-center justify-start min-w-0">
              <Link href="/" className="flex min-w-0 items-center gap-3">
                <Image src="/images/logo.jpeg" alt="Ploxi Earth" width={42} height={42} className="flex-shrink-0 rounded-full ring-2 ring-primary-500/10" />
                <div className="min-w-0">
                  <span className="block truncate text-lg font-bold text-gray-900">Ploxi Earth</span>
                  <span className="hidden text-xs uppercase tracking-[0.22em] text-gray-400 xl:block">
                    Decarbonisation Marketplace
                  </span>
                </div>
              </Link>
            </div>
            <nav className="hidden lg:flex flex-shrink-0 items-center justify-center gap-1 xl:gap-4">
              {NAV_LINKS.map((item) => (
                <Link key={item.href} href={item.href} className="whitespace-nowrap rounded-full px-3 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-100 hover:text-primary-600 xl:px-4">
                  {item.label}
                </Link>
              ))}
            </nav>
            <div className="flex flex-1 items-center justify-end gap-3">
              <div className="hidden lg:flex items-center gap-2 xl:gap-3">
                <a href="#lead-capture" onClick={scrollToLeadCapture} className="btn-primary flex whitespace-nowrap items-center gap-2 px-4 py-2 text-sm transition-transform hover:-translate-y-0.5">
                  <Calendar className="h-4 w-4" />
                  Talk to Experts
                </a>
              </div>
              <button type="button" onClick={() => setMobileNavOpen(true)} className="inline-flex h-11 w-11 flex-shrink-0 items-center justify-center rounded-2xl border border-gray-200 bg-white text-gray-700 shadow-sm transition-colors hover:bg-gray-50 lg:hidden" aria-label="Open navigation">
                <Menu className="h-5 w-5" />
              </button>
            </div>
          </div>
        </header>
      </HeroFadeDown>

      {/* Mobile Nav */}
      <AnimatePresence>
        {mobileNavOpen && (
          <>
            <motion.button type="button" aria-label="Close navigation" className="fixed inset-0 z-[60] bg-slate-950/45 backdrop-blur-sm lg:hidden" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setMobileNavOpen(false)} />
            <motion.div className="fixed inset-x-4 top-4 z-[70] overflow-hidden rounded-[28px] border border-white/60 bg-white/95 p-4 shadow-2xl backdrop-blur-xl lg:hidden" initial={{ opacity: 0, y: -24, scale: 0.96 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -18, scale: 0.98 }} transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}>
              <div className="mb-4 flex items-center justify-between gap-3">
                <div className="flex min-w-0 items-center gap-3">
                  <Image src="/images/logo.jpeg" alt="Ploxi Earth" width={38} height={38} className="rounded-full" />
                  <div className="min-w-0">
                    <p className="truncate text-sm font-bold text-slate-900">Ploxi Earth</p>
                  </div>
                </div>
                <button type="button" onClick={() => setMobileNavOpen(false)} className="inline-flex h-10 w-10 items-center justify-center rounded-2xl border border-slate-200 text-slate-600 transition-colors hover:bg-slate-50">
                  <X className="h-5 w-5" />
                </button>
              </div>
              <div className="space-y-2">
                {NAV_LINKS.map((item) => (
                  <Link key={item.href} href={item.href} onClick={() => setMobileNavOpen(false)} className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/80 px-4 py-3 text-sm font-medium text-slate-700 transition-colors hover:border-primary-200 hover:bg-primary-50 hover:text-primary-700">
                    <span>{item.label}</span>
                    <ArrowRight className="h-4 w-4" />
                  </Link>
                ))}
              </div>
              <div className="mt-4 flex flex-col gap-3">
                <a href="#lead-capture" onClick={(e) => { setMobileNavOpen(false); scrollToLeadCapture(e); }} className="btn-primary flex w-full items-center justify-center gap-2 transition-transform hover:-translate-y-0.5">
                  <Calendar className="h-4 w-4" />
                  Talk to Financing Experts
                </a>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>

      {/* Hero Section */}
      <section className="relative overflow-hidden bg-slate-950 text-white pb-24 pt-20 lg:pt-28">
        <div className="absolute inset-0 bg-gradient-to-bl from-slate-900 via-slate-950 to-emerald-950/30" />
        <div className="absolute left-0 top-1/4 h-96 w-96 rounded-full bg-emerald-500/10 blur-[120px] pointer-events-none" />
        <div className="absolute right-0 bottom-0 h-96 w-96 rounded-full bg-cyan-500/10 blur-[120px] pointer-events-none" />

        <div className="relative mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8 z-10">
          <HeroFadeUp delay={0.1}>
            <div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-500/15 px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">
              Clean Energy Financing
            </div>
          </HeroFadeUp>
          <HeroFadeUp delay={0.2}>
            <h1 className="mt-8 text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-7xl text-balance">
              Accelerate Renewable <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-300">Energy Adoption.</span>
            </h1>
          </HeroFadeUp>
          <HeroFadeUp delay={0.3}>
            <p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300 sm:text-xl">
              Access tailored financing pathways for commercial solar, wind, and storage projects. Shift to clean energy with zero upfront capital.
            </p>
          </HeroFadeUp>
          <HeroFadeUp delay={0.4}>
            <div className="mt-10 flex justify-center">
              <a href="#lead-capture" onClick={scrollToLeadCapture} className="btn-primary px-8 py-4 text-base font-semibold shadow-lg shadow-emerald-600/20">
                Talk to Renewable Financing Experts
              </a>
            </div>
          </HeroFadeUp>
        </div>
      </section>

      {/* Project Examples */}
      <section className="bg-slate-50 py-24 border-b border-gray-100">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-gray-900">
              Fund the Future of Your Facility
            </h2>
            <p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">
              We structure financing for diverse clean energy assets, turning unused space into revenue-generating power plants.
            </p>
          </FadeUp>

          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {PROJECT_EXAMPLES.map((project) => (
              <StaggerItem key={project.title} className="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm hover:shadow-md transition">
                <div className={`mb-6 inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${project.color} text-white shadow-lg`}>
                  {project.icon}
                </div>
                <h3 className="text-2xl font-bold text-gray-900 mb-4">{project.title}</h3>
                <p className="text-gray-600 leading-relaxed">{project.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* ROI & Calculator Section */}
      <section className="bg-white py-24 overflow-hidden">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            
            <FadeUp>
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 mb-6">
                Positive ROI from <span className="text-primary-600">Day One</span>
              </h2>
              <p className="text-lg text-gray-600 mb-8">
                Transitioning to renewable energy is no longer just an environmental decision—it's a financial imperative. By locking in energy rates, you hedge against utility inflation and generate immediate cash flow.
              </p>
              
              <ul className="space-y-4 mb-8">
                {[
                  'Eliminate utility rate volatility',
                  'Zero out-of-pocket costs with PPA structures',
                  'Increase your property value',
                  'Leverage MACRS depreciation and tax credits',
                ].map((item, idx) => (
                  <li key={idx} className="flex gap-3">
                    <CheckCircle2 className="h-6 w-6 flex-shrink-0 text-emerald-500" />
                    <span className="text-gray-700 font-medium">{item}</span>
                  </li>
                ))}
              </ul>
            </FadeUp>

            {/* Interactive Calculator Mockup UI */}
            <FadeUp delay={0.2} className="relative">
              <div className="absolute -inset-4 bg-gradient-to-tr from-emerald-100 to-cyan-100 rounded-[2.5rem] transform -rotate-2 opacity-50" />
              <div className="relative bg-slate-900 rounded-3xl border border-slate-700 shadow-2xl p-8 text-white">
                <div className="flex items-center gap-3 mb-8 pb-4 border-b border-slate-800">
                  <Calculator className="h-6 w-6 text-emerald-400" />
                  <h3 className="text-xl font-bold text-slate-100">Estimated 20-Year Savings</h3>
                </div>
                
                <div className="mb-8">
                  <label className="block text-sm font-medium text-slate-400 mb-4">
                    Average Monthly Utility Bill: <span className="text-white font-bold">${sliderValue.toLocaleString()}</span>
                  </label>
                  <input 
                    type="range" 
                    min="2000" 
                    max="100000" 
                    step="1000" 
                    value={sliderValue} 
                    onChange={(e) => setSliderValue(Number(e.target.value))}
                    className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-emerald-500"
                  />
                  <div className="flex justify-between text-xs text-slate-500 mt-2">
                    <span>$2k</span>
                    <span>$100k+</span>
                  </div>
                </div>

                <div className="bg-slate-800 rounded-2xl p-6 border border-slate-700 text-center">
                  <p className="text-sm text-slate-400 mb-2">Projected Gross Savings (Ownership Model)</p>
                  <div className="text-4xl font-black text-emerald-400 mb-2">
                    {calculatedSavings}
                  </div>
                  <p className="text-xs text-slate-500">*Assumes 4% annual utility escalation rate.</p>
                </div>
              </div>
            </FadeUp>
          </div>
        </div>
      </section>

      {/* Financing Options */}
      <section className="bg-slate-50 py-24 border-y border-gray-100">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900">Flexible Financing Options</h2>
            <p className="mt-4 text-gray-600 text-lg max-w-2xl mx-auto">We model multiple scenarios so you can choose the pathway that best fits your balance sheet.</p>
          </FadeUp>
          
          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {FINANCING_OPTIONS.map((item) => (
              <StaggerItem key={item.title} className="bg-white rounded-3xl p-8 border border-gray-200 shadow-sm hover:-translate-y-1 transition duration-300">
                <div className={`mb-6 inline-flex h-14 w-14 items-center justify-center rounded-2xl ${item.bg} border ${item.border} ${item.accent}`}>
                  {item.icon}
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{item.title}</h3>
                <p className="text-gray-600 leading-relaxed">{item.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* Funding Workflow */}
      <section className="bg-slate-900 py-24 text-white relative overflow-hidden">
        <div className="absolute right-0 top-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary-900/20 rounded-full blur-[100px] pointer-events-none" />
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 relative z-10">
          <FadeUp className="text-center mb-16">
            <h2 className="text-3xl font-bold">The Funding Workflow</h2>
            <p className="mt-4 text-slate-400 text-lg">A seamless process from analysis to energization.</p>
          </FadeUp>
          
          <StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {WORKFLOW.map((step, idx) => (
              <StaggerItem key={idx} className="bg-slate-800 border border-slate-700 rounded-2xl p-6 relative overflow-hidden group hover:border-emerald-500/50 transition">
                <div className="absolute -right-4 -top-4 text-8xl font-black text-slate-700/30 group-hover:text-emerald-500/10 transition">
                  {step.step}
                </div>
                <div className="relative z-10">
                  <h3 className="text-xl font-bold text-emerald-400 mb-3">{step.title}</h3>
                  <p className="text-slate-300 text-sm">{step.desc}</p>
                </div>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* FAQs */}
      <section className="bg-white py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-12">
            <h2 className="text-3xl font-bold text-gray-900">Financing FAQ</h2>
          </FadeUp>
          <div className="space-y-4">
            {FAQS.map((faq, idx) => (
              <div key={idx} className="bg-slate-50 border border-gray-200 rounded-2xl overflow-hidden">
                <button
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-6 py-5 flex items-center justify-between font-semibold text-gray-900 hover:bg-gray-100 transition"
                >
                  <span className="text-left">{faq.question}</span>
                  <ChevronDown className={`h-5 w-5 text-gray-500 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                <AnimatePresence>
                  {openFaq === idx && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="px-6 pb-5 text-gray-600 text-sm"
                    >
                      {faq.answer}
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Lead Capture Form Section */}
      <section id="lead-capture" className="bg-slate-50 py-24 relative overflow-hidden">
        <div className="absolute left-0 top-0 h-full w-1/3 bg-gradient-to-r from-emerald-50 to-transparent pointer-events-none" />
        
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="bg-slate-900 rounded-[2.5rem] overflow-hidden shadow-2xl flex flex-col lg:flex-row-reverse">
            {/* Right Info */}
            <div className="lg:w-5/12 p-10 sm:p-14 bg-gradient-to-bl from-emerald-900 to-slate-900 text-white flex flex-col justify-center">
              <Sun className="h-12 w-12 text-emerald-400 mb-6" />
              <h2 className="text-3xl font-bold mb-4">Talk to Financing Experts</h2>
              <p className="text-emerald-100/80 mb-8">
                Ready to explore solar and storage for your facility? Provide a few details, and we'll generate a preliminary savings analysis.
              </p>
              <div className="space-y-4">
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Free preliminary financial model
                </div>
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Multiple funding pathways
                </div>
                <div className="flex items-center gap-3 text-sm text-emerald-100">
                  <CheckCircle2 className="h-5 w-5 text-emerald-400" /> Expert incentive guidance
                </div>
              </div>
            </div>

            {/* Left Form */}
            <div className="lg:w-7/12 p-10 sm:p-14 bg-white">
              <form className="space-y-6" onSubmit={(e) => e.preventDefault()}>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="name" className="text-sm font-medium text-gray-700">Full Name</label>
                    <input type="text" id="name" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="John Doe" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="email" className="text-sm font-medium text-gray-700">Work Email</label>
                    <input type="email" id="email" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="john@company.com" />
                  </div>
                </div>
                
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="company" className="text-sm font-medium text-gray-700">Company Name</label>
                    <input type="text" id="company" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition" placeholder="Acme Logistics" />
                  </div>
                  <div className="space-y-2">
                    <label htmlFor="bill" className="text-sm font-medium text-gray-700">Avg. Monthly Utility Bill</label>
                    <select id="bill" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm bg-white focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition text-gray-700">
                      <option value="">Select range...</option>
                      <option value="under5k">&lt; $5,000</option>
                      <option value="5k-20k">$5,000 - $20,000</option>
                      <option value="20k-50k">$20,000 - $50,000</option>
                      <option value="over50k">&gt; $50,000</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-2">
                  <label htmlFor="interest" className="text-sm font-medium text-gray-700">Interested Technologies</label>
                  <select id="interest" className="w-full rounded-xl border border-gray-300 px-4 py-3 text-sm bg-white focus:border-primary-500 focus:outline-none focus:ring-1 focus:ring-primary-500 transition text-gray-700">
                    <option value="">Select interest...</option>
                    <option value="solar">Commercial Solar</option>
                    <option value="storage">Battery Storage</option>
                    <option value="both">Solar + Storage</option>
                    <option value="wind">Wind Energy</option>
                    <option value="unsure">Not Sure / Advisory Needed</option>
                  </select>
                </div>

                <button type="submit" className="btn-primary w-full py-4 text-base font-semibold shadow-md">
                  Request Financing Analysis
                </button>
                <p className="text-xs text-center text-gray-500 mt-4">
                  By submitting this form, you agree to our privacy policy.
                </p>
              </form>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
