'use client';

import { useState } from 'react';
import Link from 'next/link';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ArrowRight, CheckCircle2, ChevronDown, Sun, Wind, BatteryCharging,
  Calculator, Banknote, TrendingDown, PieChart, Calendar
} from 'lucide-react';
import Footer from '@/components/Footer';
import { HeroFadeUp, FadeUp, StaggerContainer, StaggerItem } from '@/components/ui/Motion';

const CALENDLY_URL = 'https://calendly.com/dhwani-sg/30min';

const FINANCING_OPTIONS = [
  { title: 'Power Purchase Agreements (PPA)', description: 'Zero upfront cost. You agree to purchase the power generated by the solar system at a fixed, lower rate than the grid for 15–25 years.', icon: <Banknote className="h-6 w-6" />, accent: 'text-emerald-500', bg: 'bg-emerald-500/10', border: 'border-emerald-500/20' },
  { title: 'Green Loans / CAPEX', description: 'Direct ownership of the asset using tailored green financing. Claim 100% of the tax incentives, depreciation benefits, and long-term free energy.', icon: <Calculator className="h-6 w-6" />, accent: 'text-blue-500', bg: 'bg-blue-500/10', border: 'border-blue-500/20' },
  { title: 'Operating Leases', description: 'Pay a fixed monthly fee to lease the equipment. Immediate utility savings often outweigh the lease payment, generating instant positive cash flow.', icon: <PieChart className="h-6 w-6" />, accent: 'text-purple-500', bg: 'bg-purple-500/10', border: 'border-purple-500/20' },
];

const PROJECT_EXAMPLES = [
  { title: 'Commercial Solar', description: 'Rooftop, ground-mount, and carport solar arrays for factories, warehouses, and corporate campuses.', icon: <Sun className="h-8 w-8" />, color: 'from-amber-400 to-orange-500' },
  { title: 'Wind Energy', description: 'Utility-scale and distributed wind projects providing high-yield renewable baseload generation.', icon: <Wind className="h-8 w-8" />, color: 'from-blue-400 to-cyan-500' },
  { title: 'Battery Energy Storage (BESS)', description: 'Peak shaving, grid resilience, and load shifting to maximize the value of intermittent renewable generation.', icon: <BatteryCharging className="h-8 w-8" />, color: 'from-emerald-400 to-teal-500' },
];

const WORKFLOW = [
  { step: '1', title: 'Energy Profiling', desc: 'We analyze your 12-month utility interval data to determine optimal system size.' },
  { step: '2', title: 'Financial Modeling', desc: 'Comparing PPA, Lease, and Loan options to find your highest ROI pathway.' },
  { step: '3', title: 'Lender Matching', desc: 'Connecting you with our network of specialized green lenders and climate funds.' },
  { step: '4', title: 'Deployment', desc: 'Securing capital and proceeding to EPC contracting and construction.' },
];

const FAQS = [
  { question: 'What is a Power Purchase Agreement (PPA)?', answer: 'A PPA is a financial arrangement where a third-party developer owns, operates, and maintains the photovoltaic (PV) system, and you agree to site the system on your property and purchase the system\'s electric output for a predetermined period.' },
  { question: 'Are there government tax incentives available?', answer: 'Yes, depending on your jurisdiction, there are substantial incentives. For example, in the US, the Investment Tax Credit (ITC) offers a 30%+ tax credit. We factor all available local and national incentives into your financial model.' },
  { question: 'How long does the financing approval take?', answer: 'Standard green loan or lease approvals typically take 2–4 weeks once all financial data is submitted. Complex, large-scale PPAs may take 2–3 months to fully execute.' },
  { question: 'Will solar actually save me money?', answer: 'Yes. With utility rates historically rising 3–5% annually, locking in a lower, fixed energy rate through a PPA or eliminating your bill through ownership yields millions in long-term savings for commercial facilities.' },
];

export default function RenewableFinancingPage() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [sliderValue, setSliderValue] = useState(15000);
  const calculatedSavings = (sliderValue * 12 * 0.4 * 20).toLocaleString('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 });

  return (
    <div className="page-shell min-h-screen bg-slate-50">
      {/* Hero */}
      <section className="relative overflow-hidden bg-slate-950 text-white pb-20 pt-20 lg:pt-28">
        <div className="absolute inset-0 bg-gradient-to-bl from-slate-900 via-slate-950 to-emerald-950/30" />
        <div className="absolute left-0 top-1/4 h-96 w-96 rounded-full bg-emerald-500/10 blur-[120px] pointer-events-none" />
        <div className="absolute right-0 bottom-0 h-96 w-96 rounded-full bg-cyan-500/10 blur-[120px] pointer-events-none" />
        <div className="relative mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8 z-10">
          <HeroFadeUp delay={0.1}><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/25 bg-emerald-500/15 px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-emerald-300">Clean Energy Financing</div></HeroFadeUp>
          <HeroFadeUp delay={0.2}><h1 className="mt-8 text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl text-balance">Accelerate Renewable <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-300">Energy Adoption.</span></h1></HeroFadeUp>
          <HeroFadeUp delay={0.3}><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">Access tailored financing pathways for commercial solar, wind, and storage projects. Shift to clean energy with zero upfront capital.</p></HeroFadeUp>
          <HeroFadeUp delay={0.4}>
            <div className="mt-10 flex flex-col justify-center gap-4 sm:flex-row">
              <a href={CALENDLY_URL} target="_blank" rel="noopener noreferrer" className="btn-primary px-8 py-4 text-base font-semibold shadow-lg flex items-center gap-2 justify-center" id="hero-cta-renewable"><Calendar className="h-5 w-5" />Talk to Financing Experts</a>
              <Link href="/solutions/markets-financing" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/5 px-8 py-4 text-base font-semibold text-white transition-all hover:bg-white/10">View Financing Services <ArrowRight className="h-4 w-4" /></Link>
            </div>
          </HeroFadeUp>
        </div>
      </section>

      {/* Project Examples */}
      <section className="bg-slate-50 py-20 border-b border-gray-100">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-12"><h2 className="text-3xl font-bold tracking-tight text-gray-900">Fund the Future of Your Facility</h2><p className="mt-4 text-lg text-gray-600 max-w-2xl mx-auto">We structure financing for diverse clean energy assets, turning unused space into revenue-generating power plants.</p></FadeUp>
          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {PROJECT_EXAMPLES.map((project) => (
              <StaggerItem key={project.title} className="bg-white rounded-3xl p-8 border border-gray-100 shadow-sm hover:shadow-md transition">
                <div className={`mb-6 inline-flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br ${project.color} text-white shadow-lg`}>{project.icon}</div>
                <h3 className="text-2xl font-bold text-gray-900 mb-4">{project.title}</h3>
                <p className="text-gray-600 leading-relaxed">{project.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* ROI Calculator */}
      <section className="bg-white py-20 overflow-hidden">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <FadeUp>
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 mb-6">Positive ROI from <span className="text-primary-600">Day One</span></h2>
              <p className="text-lg text-gray-600 mb-8">Transitioning to renewable energy is no longer just an environmental decision — it's a financial imperative. Lock in energy rates and generate immediate cash flow.</p>
              <ul className="space-y-4 mb-8">
                {['Eliminate utility rate volatility', 'Zero out-of-pocket costs with PPA structures', 'Increase your property value', 'Leverage MACRS depreciation and tax credits'].map((item, idx) => (
                  <li key={idx} className="flex gap-3"><CheckCircle2 className="h-6 w-6 flex-shrink-0 text-emerald-500" /><span className="text-gray-700 font-medium">{item}</span></li>
                ))}
              </ul>
            </FadeUp>
            <FadeUp delay={0.2} className="relative">
              <div className="absolute -inset-4 bg-gradient-to-tr from-emerald-100 to-cyan-100 rounded-[2.5rem] transform -rotate-2 opacity-50" />
              <div className="relative bg-slate-900 rounded-3xl border border-slate-700 shadow-2xl p-8 text-white">
                <div className="flex items-center gap-3 mb-8 pb-4 border-b border-slate-800"><Calculator className="h-6 w-6 text-emerald-400" /><h3 className="text-xl font-bold text-slate-100">Estimated 20-Year Savings</h3></div>
                <div className="mb-8">
                  <label className="block text-sm font-medium text-slate-400 mb-4">Average Monthly Utility Bill: <span className="text-white font-bold">${sliderValue.toLocaleString()}</span></label>
                  <input type="range" min="2000" max="100000" step="1000" value={sliderValue} onChange={(e) => setSliderValue(Number(e.target.value))} className="w-full h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-emerald-500" id="roi-calculator-slider" />
                  <div className="flex justify-between text-xs text-slate-500 mt-2"><span>$2k</span><span>$100k+</span></div>
                </div>
                <div className="bg-slate-800 rounded-2xl p-6 border border-slate-700 text-center">
                  <p className="text-sm text-slate-400 mb-2">Projected Gross Savings (Ownership Model)</p>
                  <div className="text-4xl font-black text-emerald-400 mb-2">{calculatedSavings}</div>
                  <p className="text-xs text-slate-500">*Assumes 4% annual utility escalation rate.</p>
                </div>
              </div>
            </FadeUp>
          </div>
        </div>
      </section>

      {/* Financing Options */}
      <section className="bg-slate-50 py-20 border-y border-gray-100">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-12"><h2 className="text-3xl font-bold text-gray-900">Flexible Financing Options</h2><p className="mt-4 text-gray-600 text-lg max-w-2xl mx-auto">We model multiple scenarios so you can choose the pathway that best fits your balance sheet.</p></FadeUp>
          <StaggerContainer className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {FINANCING_OPTIONS.map((item) => (
              <StaggerItem key={item.title} className="bg-white rounded-3xl p-8 border border-gray-200 shadow-sm hover:-translate-y-1 transition duration-300">
                <div className={`mb-6 inline-flex h-14 w-14 items-center justify-center rounded-2xl ${item.bg} border ${item.border} ${item.accent}`}>{item.icon}</div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">{item.title}</h3>
                <p className="text-gray-600 leading-relaxed">{item.description}</p>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* Workflow */}
      <section className="bg-slate-900 py-20 text-white relative overflow-hidden">
        <div className="absolute right-0 top-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-primary-900/20 rounded-full blur-[100px] pointer-events-none" />
        <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8 relative z-10">
          <FadeUp className="text-center mb-12"><h2 className="text-3xl font-bold">The Funding Workflow</h2><p className="mt-4 text-slate-400 text-lg">A seamless process from analysis to energization.</p></FadeUp>
          <StaggerContainer className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {WORKFLOW.map((step, idx) => (
              <StaggerItem key={idx} className="bg-slate-800 border border-slate-700 rounded-2xl p-6 relative overflow-hidden group hover:border-emerald-500/50 transition">
                <div className="absolute -right-4 -top-4 text-8xl font-black text-slate-700/30 group-hover:text-emerald-500/10 transition">{step.step}</div>
                <div className="relative z-10"><h3 className="text-xl font-bold text-emerald-400 mb-3">{step.title}</h3><p className="text-slate-300 text-sm">{step.desc}</p></div>
              </StaggerItem>
            ))}
          </StaggerContainer>
        </div>
      </section>

      {/* FAQs */}
      <section className="bg-white py-20">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <FadeUp className="text-center mb-12"><h2 className="text-3xl font-bold text-gray-900">Financing FAQ</h2></FadeUp>
          <div className="space-y-4">
            {FAQS.map((faq, idx) => (
              <div key={idx} className="bg-slate-50 border border-gray-200 rounded-2xl overflow-hidden">
                <button onClick={() => setOpenFaq(openFaq === idx ? null : idx)} className="w-full px-6 py-5 flex items-center justify-between font-semibold text-gray-900 hover:bg-gray-100 transition" id={`faq-renewable-${idx}`}>
                  <span className="text-left">{faq.question}</span><ChevronDown className={`h-5 w-5 text-gray-500 transition-transform ${openFaq === idx ? 'rotate-180' : ''}`} />
                </button>
                <AnimatePresence>{openFaq === idx && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="px-6 pb-5 text-gray-600 text-sm">{faq.answer}</motion.div>}</AnimatePresence>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-gradient-to-br from-slate-900 via-emerald-950 to-slate-950 py-20 relative overflow-hidden">
        <div className="absolute left-0 top-0 h-80 w-80 rounded-full bg-emerald-500/10 blur-[120px]" />
        <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 text-center z-10">
          <FadeUp>
            <Sun className="h-14 w-14 text-emerald-400 mx-auto mb-6" />
            <h2 className="text-3xl sm:text-4xl font-bold text-white mb-6">Ready to Go Solar or Storage?</h2>
            <p className="text-emerald-100/80 text-lg mb-10 max-w-2xl mx-auto">Book a free 30-minute consultation. We'll generate a preliminary savings analysis and recommend the optimal financing pathway for your facility.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a href={CALENDLY_URL} target="_blank" rel="noopener noreferrer" className="btn-primary px-8 py-4 text-base font-semibold shadow-lg flex items-center gap-2 justify-center" id="bottom-cta-renewable"><Calendar className="h-5 w-5" />Book a Free Consultation</a>
              <Link href="/solutions" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/20 bg-white/5 px-8 py-4 text-base font-semibold text-white transition-all hover:bg-white/10">View All Services <ArrowRight className="h-4 w-4" /></Link>
            </div>
            <div className="mt-8 flex flex-wrap justify-center gap-6 text-sm text-emerald-200/70">
              <span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Free preliminary financial model</span>
              <span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Multiple funding pathways</span>
              <span className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400" />Expert incentive guidance</span>
            </div>
          </FadeUp>
        </div>
      </section>
      <Footer />
    </div>
  );
}
