// ─── Carbon Market Data ────────────────────────────────────────────────────────
// Auto-generated from Inventory Mastersheet.xlsx — do not edit manually.
// To regenerate: python generate_carbon_data.py (from project root)

export interface CarbonProject {
  id: string;
  title: string;
  source: string;
  country: string;
  registry: string;
  creditType: string;
  category: string;
  vintage: string;
  volume?: number;
  issuanceStatus: string;
  technology?: string;
  description?: string;
  sdgs?: string[];
  corsiaEligible?: string;
  loaStatus?: string;
  deliveryStatus?: string;
  deliverySchedule?: string;
  verificationCycle?: string;
}

export const CARBON_PROJECTS: CarbonProject[] = [
  {
    id: 'VCS 1347',
    title: 'Kenya Cookstove Project',
    source: 'NatureNex',
    country: 'Kenya',
    registry: 'VCS (Verra)',
    creditType: 'Reduction',
    category: 'Cookstoves',
    vintage: '2018-24',
    volume: 90000,
    issuanceStatus: 'Registered',
  },
  {
    id: 'Unspecified',
    title: '-',
    source: 'NatureNex',
    country: 'Africa',
    registry: 'Not Specified',
    creditType: 'Reduction',
    category: 'Cookstoves',
    vintage: '2025–2026',
    volume: 2583000,
    issuanceStatus: 'Approved (UNFCCC logged)',
  },
  {
    id: 'UN Ref 6974',
    title: 'Grid connected renewable electricity generation by SCCPL',
    source: 'MitCarbon',
    country: 'Tamil Nadu, India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Reduction',
    category: 'Renewable Electricity',
    vintage: '2013-2020',
    volume: 241873,
    issuanceStatus: 'Issued',
  },
  {
    id: 'UN Ref 9410',
    title: '4.25 MW Wind Power Project by Amarjothi Spinning Mills Ltd',
    source: 'MitCarbon',
    country: 'Tamil Nadu, India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Reduction',
    category: 'Wind Power',
    vintage: '2012',
    volume: 0,
    issuanceStatus: 'Issued',
  },
  {
    id: 'UN Ref 1047',
    title: '11.2 MW Wind Power Project by Amarjothi Group',
    source: 'MitCarbon',
    country: 'Tamil Nadu, India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Reduction',
    category: 'Wind Power',
    vintage: '2012',
    volume: 3250,
    issuanceStatus: 'Issued',
  },
  {
    id: '3949',
    title: 'Biogas Methane Avoidance - Bio-CNG',
    source: 'MitCarbon',
    country: 'Tamil Nadu, India',
    registry: 'Verra (VCS)',
    creditType: 'Avoidance',
    category: 'Biogas/Biogas CNG',
    vintage: '02/2021-11/2022',
    volume: 24823,
    issuanceStatus: 'Already Issued',
    sdgs: ['SDG 7', '8', '11', '13'],
    deliverySchedule: 'Already Issued',
  },
  {
    id: '4334',
    title: 'Biogas Methane Avoidance - Bio-CNG',
    source: 'MitCarbon',
    country: 'Tamil Nadu, India',
    registry: 'Verra (VCS)',
    creditType: 'Avoidance',
    category: 'Biogas/Biogas CNG',
    vintage: '07/2021-04/2023',
    volume: 13345,
    issuanceStatus: 'Already Issued',
    sdgs: ['SDG 3', '7', '8', '13'],
    deliverySchedule: 'Already Issued',
  },
  {
    id: 'ICR 172',
    title: 'Tree Plantation Programme Phase 1',
    source: 'Crop Agro',
    country: 'India (KA, MH, AP, TG)',
    registry: 'ICR',
    creditType: 'Removal',
    category: 'Afforestation (Mahogany)',
    vintage: '2021-2025 (5 cycles)',
    volume: 41075,
    issuanceStatus: 'Mixed (2021-23: Issued, 2024-25: Pending)',
    description: 'Tree plantation programme in different states of India- Phase 1 is an afforestation project, implemented in India by Cropcity Agro Carbons Private Limited (CAPL), in coordination with the subsistence farmers. At present CAPL has a large group of farmers cultivating Mahogany trees in states of Karnataka, Maharashtra, Andhra Pradesh, and Telangana located in India',
    sdgs: ['SDG 1', '8', '13', '15'],
    deliverySchedule: 'On Spot Delivery- Since Issuance of credits already done and avaiable for immeadite trade',
    verificationCycle: '1st Verification',
  },
  {
    id: 'GCR 19',
    title: 'Tree Plantation Programme Phase 2',
    source: 'Crop Agro',
    country: 'India (12 states)',
    registry: 'GCR',
    creditType: 'Removal',
    category: 'Afforestation (Mahogany)',
    vintage: '2021-2025 (5 cycles)',
    volume: 69213,
    issuanceStatus: 'Issued; on-spot delivery',
    description: 'It is an afforestation Project in the form of tree plantation that aims to satisfy multiple Sustainable Development goals through Project activity. The Project is implemented on multiple scattered small land areas (farmlands) across the states of Andhra Pradesh, Arunachal Pradesh, Chhattisgarh, Gujarat, Jharkhand, Karnataka, Madhya Pradesh, Maharashtra, Odisha, Tamil Nadu, Telangana, and Uttara Pr',
    sdgs: ['SDG 1', '8', '13', '15'],
    deliverySchedule: 'On Spot Delivery- Since Issuance of credits already done and avaiable for immeadite trade',
    verificationCycle: '1st Verification',
  },
  {
    id: 'GS 12293',
    title: 'Renew Sakhi Improved Cookstove - 2',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'CSA',
    category: 'Reduction',
    vintage: '2023',
    volume: 47838,
    issuanceStatus: 'Issued',
    technology: 'ICS',
  },
  {
    id: 'GS 2293',
    title: 'India Organic Waste Management Programme',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'CSA',
    category: 'Reduction',
    vintage: '2018',
    volume: 31150,
    issuanceStatus: 'Issued',
    technology: 'Household Biogas',
  },
  {
    id: 'GS3378',
    title: 'Solar Water Heater Program in India (8 VPAs)',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'CSA',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 213000,
    issuanceStatus: 'Issued',
    technology: 'Household solar water heater',
  },
  {
    id: 'GS12064',
    title: 'HomeBiogas Programme in Kenya – VPA1',
    source: 'Kosher Climate',
    country: 'Kenya',
    registry: 'Gold Standard',
    creditType: 'CSA',
    category: 'Reduction',
    vintage: '2024',
    volume: 5000,
    issuanceStatus: 'Issued',
    technology: 'Household Biogas',
  },
  {
    id: 'GS 12383',
    title: 'GS12382 VPA 01 Improved agricultural practices for rice cultivation in India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'AWD',
    category: 'Reduction',
    vintage: '2023',
    volume: 17690,
    issuanceStatus: 'Issued',
    technology: 'AWD',
  },
  {
    id: 'GS12690',
    title: 'GS12382 GS12383 RVPA-1 Improved agricultural practices for rice cultivation in India.',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'AWD',
    category: 'Reduction',
    vintage: '2024',
    volume: 42379,
    issuanceStatus: 'Issuance by July 2026',
    technology: 'AWD',
  },
  {
    id: 'GS 23159',
    title: 'GS12382 GS12383 BVPA 01 Improved agricultural practices for rice cultivation in West Bengal',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'AWD',
    category: 'Reduction',
    vintage: '2023',
    volume: 348,
    issuanceStatus: 'Issuance by July 2026',
    technology: 'AWD',
  },
  {
    id: 'GS 23160',
    title: 'GS12382 GS12383 BVPA 02 Improved agricultural practices for rice cultivation in West Bengal',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'AWD',
    category: 'Reduction',
    vintage: '2023',
    volume: 369,
    technology: 'AWD',
  },
  {
    id: 'GS 23161',
    title: 'GS12382 GS12383 BVPA 03 Improved agricultural practices for rice cultivation in West Bengal',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'AWD',
    category: 'Reduction',
    vintage: '2023',
    volume: 279,
    issuanceStatus: 'Issuance by September 2026',
    technology: 'AWD',
  },
  {
    id: 'GS 3965',
    title: '22.5 MW Wind Power Project in Rajasthan, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021',
    volume: 6000,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'GS 5523',
    title: 'Solar Power Project by Fortum FinnSurya Energy Pvt Ltd',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020',
    volume: 11591,
    issuanceStatus: 'Issued',
    technology: 'Solar',
    corsiaEligible: 'Yes',
  },
  {
    id: 'GS 5928',
    title: '2x50 MW Orange Suvaan Solar Photovoltaic Power Project in Maharashtra, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020',
    volume: 11124,
    issuanceStatus: 'Issued',
    technology: 'Solar',
    corsiaEligible: 'Yes',
  },
  {
    id: 'GS 7553',
    title: '42 MWp Bundled Solar photovoltaic power project in Indonesia',
    source: 'Kosher Climate',
    country: 'Indonesia',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021',
    volume: 55222,
    issuanceStatus: 'Issued awaiting for SRN Approval',
    technology: 'Solar',
  },
  {
    id: 'GS 7164',
    title: '72 MW wind power project in the South Sulawesi Province of Indonesia',
    source: 'Kosher Climate',
    country: 'Indonesia',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020',
    volume: 26618,
    issuanceStatus: 'Issued awaiting for SRN Approval',
    technology: 'Wind',
  },
  {
    id: 'GS 7744',
    title: 'West Huaybong 2 wind farm project',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 77225,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'GS 7746',
    title: 'West Huaybong 3 wind farm project',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2019',
    volume: 14805,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'GS 7754',
    title: 'Tuppadahalli Wind Energy Project',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2019',
    volume: 14735,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'GS 7745',
    title: '300 MW Wind Power Project in Gujarat by Alfanar',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 229761,
    issuanceStatus: 'Issued, BeZero BB Rated',
    technology: 'Wind',
  },
  {
    id: 'GS 6760',
    title: 'Guttigoli Solar Power Project in Karnataka',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 34818,
    issuanceStatus: 'Issued',
    technology: 'Solar',
  },
  {
    id: 'GS7750',
    title: '96.8 MW Wind Power Project in Amreli, Gujarat',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020',
    volume: 4906,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'GS7751',
    title: '75 MW Neo Solar Power Project',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021',
    volume: 8323,
    issuanceStatus: 'Issued',
    technology: 'Solar',
  },
  {
    id: 'GS 7533',
    title: '100 MW Solar Power Plant in Maharashtra',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2023',
    volume: 87730,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'GS 7572',
    title: '120 MW Solar PV Plant by Juniper Green Sigma Private Ltd. in Gujarat',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2023',
    volume: 16188,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'GS 7627',
    title: '150 MW Solar PV Plant by Juniper Green Field Pvt. Ltd. in Maharashtra',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2024',
    volume: 298479,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'GS 7727',
    title: '250 MW Solar PV Plant at Bhainsada, Rajasthan',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 789740,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'GS 6290',
    title: '200 MW Wind Power Project in Tamil Nadu by Orange Sironj',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021 - 2022',
    volume: 623001,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'GS 7678',
    title: '300 MW Wind Power Project by Sitac Kabini in Gujarat',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Gold Standard',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 76572,
    issuanceStatus: 'Issued, BeZero BB Rated (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 2065',
    title: 'Renewable Energy Power Projects by Atria Power',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 157655,
    issuanceStatus: 'Issued',
    technology: 'Wind & Solar',
  },
  {
    id: 'VCS 1746',
    title: '108 MW Fatanpur Wind Power Project in Madhya Pradesh',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 182709,
    issuanceStatus: 'Issuance by June 2026',
    technology: 'Wind',
  },
  {
    id: 'VCS 1771',
    title: '46 MW Mangoli Wind Power Project',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020',
    volume: 80937,
    issuanceStatus: 'Issued',
    technology: 'Wind',
    corsiaEligible: 'Yes',
  },
  {
    id: 'VCS 1893',
    title: '18 MW Kemphole Mini Hydel Scheme (KMHS), by International Power Corporation Limited, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2017',
    volume: 3611,
    issuanceStatus: 'Issued',
    technology: 'Hydro',
  },
  {
    id: 'VCS 3662',
    title: '15 MW Nam Hinboun Downstream Hydropower Project',
    source: 'Kosher Climate',
    country: 'Lao PDR',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 8501,
    issuanceStatus: 'Issued. CORSIA LoA application under progress',
    technology: 'Small Hydro',
  },
  {
    id: 'VC4588',
    title: 'Nam Houng - 1 Hydro Power Project',
    source: 'Kosher Climate',
    country: 'Lao PDR',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2023',
    volume: 8687,
    issuanceStatus: 'Issued. CORSIA LoA application under progress',
  },
  {
    id: 'VCS 2002',
    title: 'Theparak wind in Thailand',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 384,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 1999',
    title: 'KRISSANA WIND POWER IN THAILAND',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 57800,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 1997',
    title: 'TROPICAL WIND IN THAILAND',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 64599,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 2000',
    title: 'K.R.S. THREE IN THAILAND',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 62339,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 2001',
    title: 'K.R. ONE IN THAILAND',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 55593,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 1042',
    title: 'Oaxaca III Wind Energy Project',
    source: 'Kosher Climate',
    country: 'Mexico',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021',
    volume: 28741,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'VCS 4869',
    title: 'Kampong Chhnang 60 MW solar power project',
    source: 'Kosher Climate',
    country: 'Cambodia',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 10264,
    issuanceStatus: 'Issued. A6 LoA application under progress',
    technology: 'Solar',
    corsiaEligible: 'Yes',
  },
  {
    id: 'VCS 1786',
    title: 'Solar Photovoltaic Project by Giriraj Renewables Private Limited',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021 - 2023',
    volume: 440000,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'VCS 1914',
    title: '150 MW Solar Project in Karnataka by Avaada Solar',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021 - 2023',
    volume: 438287,
    issuanceStatus: 'Issued. BeZero \'B\' Rated (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'VCS 1792',
    title: 'Ghani Solar Renewable Power Project by Greenko Group',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2021 - 2022',
    volume: 1262357,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'VCS 1039',
    title: 'AES Saurashtra Windfarms',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2012-2021',
    volume: 573642,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1109',
    title: 'Mithapur solar power project',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020-2022',
    volume: 69976,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'VCS 3556',
    title: 'Grouped rooftop solar project by Tata Power Renewable Energy Limited',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020-2022',
    volume: 52309,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
  },
  {
    id: 'VCS 2019',
    title: '100 MW Grid Connected Wind Power Project in Jamnagar, Gujarat, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2019',
    volume: 42500,
    issuanceStatus: 'Issued. BeZero \'BB\' Rated (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1784',
    title: 'Solar Power Project by Mytrah Energy India Pvt.Ltd',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 283535,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Solar',
    corsiaEligible: 'Yes',
  },
  {
    id: 'VCS 1521',
    title: 'Wind Based Power Generation by Mytrah Energy (India) Limited (EKIESL-VCS-January-16-01)',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 582986,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1523',
    title: 'Wind Based Power Generation by Panama Wind Energy Godawari Private Limited, Pune in the State of Maharashtra, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 145832,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1671',
    title: 'Wind based power generation by Panama Wind Energy Private Limited in Maharashtra, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022',
    volume: 77937,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1728',
    title: 'Bundled Wind Power Project by Mytrah Group',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 1614093,
    issuanceStatus: 'Issued. BeZero \'B\' Rated (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS2020',
    title: '250 MW Wind Power Project by Mytrah Energy',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2022-2024',
    volume: 914213,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Wind',
  },
  {
    id: 'VCS 1742',
    title: 'Hydroelectric Project in Kinnaur District in Himachal Pradesh',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2014-2022',
    volume: 15093525,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Hydro',
  },
  {
    id: 'VCS 92',
    title: '300MW Hydropower project by JHPL',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2018-2024',
    volume: 5816432,
    issuanceStatus: 'Issued. BeZero \'B\' Rated (Non-exclusive to Kosher)',
    technology: 'Hydro',
  },
  {
    id: 'VCS 2887',
    title: 'Boomitra Grassland Restoration in Northern Mexico',
    source: 'Kosher Climate',
    country: 'Mexico',
    registry: 'Verra (VCS)',
    creditType: 'NBS',
    category: 'Removal',
    vintage: '2019-2022',
    volume: 3500000,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Grassland SOC',
  },
  {
    id: 'VCS 3570',
    title: 'Bamboo plantations by farmers and community in the country',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'NBS',
    category: 'Removal',
    vintage: '2018-2023',
    volume: 150000,
    issuanceStatus: 'Issued (Non-exclusive to Kosher)',
    technology: 'Agroforestry',
  },
  {
    id: 'VCS 5300',
    title: 'TVS Motor Company Electric Vehicle Project in India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'Verra (VCS)',
    creditType: 'EV',
    category: 'Reduction',
    vintage: '2024',
    volume: 3537,
    issuanceStatus: 'Issuance by August 2026',
    technology: 'EV',
  },
  {
    id: 'CDM 7650',
    title: 'West Huaybong 2 wind farm project',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2015-2019',
    volume: 196525,
    issuanceStatus: 'Only Cancellation',
    technology: 'Wind',
  },
  {
    id: 'CDM 7474',
    title: 'West Huaybong 3 wind farm project',
    source: 'Kosher Climate',
    country: 'Thailand',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2015-2019',
    volume: 15137,
    issuanceStatus: 'Only Cancellation',
    technology: 'Wind',
  },
  {
    id: 'CDM 312 CP1',
    title: '18 MW Kemphole Mini Hydel Scheme (KMHS)',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2010-2012',
    volume: 39272,
    issuanceStatus: 'Only Cancellation',
    technology: 'Hydro',
  },
  {
    id: 'CDM 312 CP2',
    title: '18 MW Kemphole Mini Hydel Scheme (KMHS)',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2013-2016',
    volume: 83225,
    issuanceStatus: 'Only Cancellation',
    technology: 'Hydro',
  },
  {
    id: 'CDM 6366',
    title: '4.00 MW Bundled Wind Power Project at RJ & MH, India',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2013-2020',
    volume: 28380,
    issuanceStatus: 'Only Cancellation',
    technology: 'Wind',
  },
  {
    id: 'CDM 6401',
    title: 'Biomass based Co-generation plant at Nagda, MP, India.',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2013-2020',
    volume: 529083,
    issuanceStatus: 'Only Cancellation',
    technology: 'Cogeneration',
  },
  {
    id: 'CDM 6056',
    title: 'Proposed 4.2 MW wind power project',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2012-2019',
    volume: 35626,
    issuanceStatus: 'Only Cancellation',
    technology: 'Wind',
  },
  {
    id: 'CDM 3575',
    title: '3.0 MW Wind energy project in Karnataka',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'CDM (UNFCCC)',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2012-2020',
    volume: 43376,
    issuanceStatus: 'Only Cancellation',
    technology: 'Wind',
  },
  {
    id: 'S00559',
    title: '220 MW Wind Project in TN',
    source: 'Kosher Climate',
    country: 'India',
    registry: 'GCC',
    creditType: 'Renewables',
    category: 'Reduction',
    vintage: '2020-2023',
    volume: 1680814,
    issuanceStatus: 'Issued',
    technology: 'Wind',
  },
  {
    id: 'PWRP 5002',
    title: 'POLIBALBINO RECYCLING PROJECT IN BRAZIL',
    source: 'Kosher Climate',
    country: 'Brazil',
    registry: 'Verra (Plastic Program)',
    creditType: 'Plastic Waste Recycling',
    category: 'Reduction/Avoidance',
    vintage: '2018-2023',
    volume: 14639,
    issuanceStatus: 'Issued',
    technology: 'Plastic waste recycling',
  },
];

// ─── Portfolio Statistics ────────────────────────────────────────────────────
export function computePortfolioStats(projects: CarbonProject[]) {
  const totalVolume = projects.reduce((s, p) => s + (p.volume ?? 0), 0);
  const countries = new Set(projects.map(p => p.country)).size;
  const categories = new Set(projects.map(p => p.category)).size;
  const registries = new Set(projects.map(p => p.registry)).size;
  const vintages = new Set(projects.map(p => p.vintage)).size;
  return { totalProjects: projects.length, totalVolume, countries, categories, registries, vintages };
}

// ─── Filter Option Extractors ────────────────────────────────────────────────
export function getFilterOptions(projects: CarbonProject[]) {
  const uniq = <T,>(arr: T[]) => [...new Set(arr)].filter(Boolean).sort() as T[];
  return {
    categories: uniq(projects.map(p => p.category)),
    creditTypes: uniq(projects.map(p => p.creditType)),
    registries: uniq(projects.map(p => p.registry)),
    countries: uniq(projects.map(p => p.country)),
    sources: uniq(projects.map(p => p.source)),
    statuses: uniq(projects.map(p => p.issuanceStatus)),
  };
}

// ─── Filter & Search ─────────────────────────────────────────────────────────
export interface ProjectFilters {
  search?: string;
  category?: string;
  creditType?: string;
  registry?: string;
  country?: string;
  source?: string;
  status?: string;
  sortBy?: 'title' | 'vintage' | 'volume' | 'country';
  sortDir?: 'asc' | 'desc';
}

export function filterAndSort(projects: CarbonProject[], filters: ProjectFilters): CarbonProject[] {
  const q = (filters.search || '').toLowerCase().trim();
  let result = projects.filter(p => {
    if (q) {
      const hay = `${p.title} ${p.id} ${p.country} ${p.category} ${p.registry} ${p.creditType}`.toLowerCase();
      if (!hay.includes(q)) return false;
    }
    if (filters.category && p.category !== filters.category) return false;
    if (filters.creditType && p.creditType !== filters.creditType) return false;
    if (filters.registry && p.registry !== filters.registry) return false;
    if (filters.country && p.country !== filters.country) return false;
    if (filters.source && p.source !== filters.source) return false;
    if (filters.status && p.issuanceStatus !== filters.status) return false;
    return true;
  });
  const dir = filters.sortDir === 'desc' ? -1 : 1;
  result.sort((a, b) => {
    switch (filters.sortBy) {
      case 'vintage': return dir * a.vintage.localeCompare(b.vintage);
      case 'volume': return dir * ((a.volume ?? 0) - (b.volume ?? 0));
      case 'country': return dir * a.country.localeCompare(b.country);
      default: return dir * a.title.localeCompare(b.title);
    }
  });
  return result;
}